openhab:
  container_name: openhab
  image: "openhab/openhab:2.1.0-armhf"
  restart: always
  net: host
  cap_add:
    - NET_ADMIN
    - NET_RAW
  environment:
    USER_ID: "999"
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"
    LANGUAGE: "en_US.UTF-8"
    OPENHAB_HTTP_PORT: "8080"
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/etc/timezone:/etc/timezone:ro"
    - "openhab_conf:/openhab/conf"
    - "openhab_userdata:/openhab/userdata"
    - "openhab_addons:/openhab/addons"
  # The command node is very important. It overrides
  # the "gosu openhab ./start.sh" command from Dockerfile and runs as root!
  command: "./start.sh"